// Generated by gencpp from file second_assignment/ServiceResponse.msg
// DO NOT EDIT!


#ifndef SECOND_ASSIGNMENT_MESSAGE_SERVICERESPONSE_H
#define SECOND_ASSIGNMENT_MESSAGE_SERVICERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace second_assignment
{
template <class ContainerAllocator>
struct ServiceResponse_
{
  typedef ServiceResponse_<ContainerAllocator> Type;

  ServiceResponse_()
    : getVal(0.0)  {
    }
  ServiceResponse_(const ContainerAllocator& _alloc)
    : getVal(0.0)  {
  (void)_alloc;
    }



   typedef float _getVal_type;
  _getVal_type getVal;





  typedef boost::shared_ptr< ::second_assignment::ServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_assignment::ServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceResponse_

typedef ::second_assignment::ServiceResponse_<std::allocator<void> > ServiceResponse;

typedef boost::shared_ptr< ::second_assignment::ServiceResponse > ServiceResponsePtr;
typedef boost::shared_ptr< ::second_assignment::ServiceResponse const> ServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_assignment::ServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_assignment::ServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::second_assignment::ServiceResponse_<ContainerAllocator1> & lhs, const ::second_assignment::ServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.getVal == rhs.getVal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::second_assignment::ServiceResponse_<ContainerAllocator1> & lhs, const ::second_assignment::ServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace second_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_assignment::ServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_assignment::ServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_assignment::ServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_assignment::ServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_assignment::ServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_assignment::ServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_assignment::ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "682a4eca7e2dcef83971164d6ea2a189";
  }

  static const char* value(const ::second_assignment::ServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x682a4eca7e2dcef8ULL;
  static const uint64_t static_value2 = 0x3971164d6ea2a189ULL;
};

template<class ContainerAllocator>
struct DataType< ::second_assignment::ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_assignment/ServiceResponse";
  }

  static const char* value(const ::second_assignment::ServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_assignment::ServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 getVal\n"
"\n"
;
  }

  static const char* value(const ::second_assignment::ServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_assignment::ServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.getVal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_assignment::ServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::second_assignment::ServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "getVal: ";
    Printer<float>::stream(s, indent + "  ", v.getVal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_ASSIGNMENT_MESSAGE_SERVICERESPONSE_H
