// Generated by gencpp from file second_assignment/ServiceRequest.msg
// DO NOT EDIT!


#ifndef SECOND_ASSIGNMENT_MESSAGE_SERVICEREQUEST_H
#define SECOND_ASSIGNMENT_MESSAGE_SERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace second_assignment
{
template <class ContainerAllocator>
struct ServiceRequest_
{
  typedef ServiceRequest_<ContainerAllocator> Type;

  ServiceRequest_()
    : setVal(0)  {
    }
  ServiceRequest_(const ContainerAllocator& _alloc)
    : setVal(0)  {
  (void)_alloc;
    }



   typedef uint8_t _setVal_type;
  _setVal_type setVal;





  typedef boost::shared_ptr< ::second_assignment::ServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_assignment::ServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ServiceRequest_

typedef ::second_assignment::ServiceRequest_<std::allocator<void> > ServiceRequest;

typedef boost::shared_ptr< ::second_assignment::ServiceRequest > ServiceRequestPtr;
typedef boost::shared_ptr< ::second_assignment::ServiceRequest const> ServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_assignment::ServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_assignment::ServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::second_assignment::ServiceRequest_<ContainerAllocator1> & lhs, const ::second_assignment::ServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.setVal == rhs.setVal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::second_assignment::ServiceRequest_<ContainerAllocator1> & lhs, const ::second_assignment::ServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace second_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_assignment::ServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_assignment::ServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_assignment::ServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_assignment::ServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_assignment::ServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_assignment::ServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_assignment::ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "700f3d0ef2d3afaa15c71d548b552f53";
  }

  static const char* value(const ::second_assignment::ServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x700f3d0ef2d3afaaULL;
  static const uint64_t static_value2 = 0x15c71d548b552f53ULL;
};

template<class ContainerAllocator>
struct DataType< ::second_assignment::ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_assignment/ServiceRequest";
  }

  static const char* value(const ::second_assignment::ServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_assignment::ServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "char setVal\n"
;
  }

  static const char* value(const ::second_assignment::ServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_assignment::ServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.setVal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_assignment::ServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::second_assignment::ServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "setVal: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.setVal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_ASSIGNMENT_MESSAGE_SERVICEREQUEST_H
