// Generated by gencpp from file second_assignment/Service.msg
// DO NOT EDIT!


#ifndef SECOND_ASSIGNMENT_MESSAGE_SERVICE_H
#define SECOND_ASSIGNMENT_MESSAGE_SERVICE_H

#include <ros/service_traits.h>


#include <second_assignment/ServiceRequest.h>
#include <second_assignment/ServiceResponse.h>


namespace second_assignment
{

struct Service
{

typedef ServiceRequest Request;
typedef ServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Service
} // namespace second_assignment


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::second_assignment::Service > {
  static const char* value()
  {
    return "4f1064e684dd3d6da99d55dc37eb289e";
  }

  static const char* value(const ::second_assignment::Service&) { return value(); }
};

template<>
struct DataType< ::second_assignment::Service > {
  static const char* value()
  {
    return "second_assignment/Service";
  }

  static const char* value(const ::second_assignment::Service&) { return value(); }
};


// service_traits::MD5Sum< ::second_assignment::ServiceRequest> should match
// service_traits::MD5Sum< ::second_assignment::Service >
template<>
struct MD5Sum< ::second_assignment::ServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::second_assignment::Service >::value();
  }
  static const char* value(const ::second_assignment::ServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::second_assignment::ServiceRequest> should match
// service_traits::DataType< ::second_assignment::Service >
template<>
struct DataType< ::second_assignment::ServiceRequest>
{
  static const char* value()
  {
    return DataType< ::second_assignment::Service >::value();
  }
  static const char* value(const ::second_assignment::ServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::second_assignment::ServiceResponse> should match
// service_traits::MD5Sum< ::second_assignment::Service >
template<>
struct MD5Sum< ::second_assignment::ServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::second_assignment::Service >::value();
  }
  static const char* value(const ::second_assignment::ServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::second_assignment::ServiceResponse> should match
// service_traits::DataType< ::second_assignment::Service >
template<>
struct DataType< ::second_assignment::ServiceResponse>
{
  static const char* value()
  {
    return DataType< ::second_assignment::Service >::value();
  }
  static const char* value(const ::second_assignment::ServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SECOND_ASSIGNMENT_MESSAGE_SERVICE_H
