// Generated by gencpp from file second_assignment/Speed.msg
// DO NOT EDIT!


#ifndef SECOND_ASSIGNMENT_MESSAGE_SPEED_H
#define SECOND_ASSIGNMENT_MESSAGE_SPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace second_assignment
{
template <class ContainerAllocator>
struct Speed_
{
  typedef Speed_<ContainerAllocator> Type;

  Speed_()
    : acSpeed(0.0)  {
    }
  Speed_(const ContainerAllocator& _alloc)
    : acSpeed(0.0)  {
  (void)_alloc;
    }



   typedef float _acSpeed_type;
  _acSpeed_type acSpeed;





  typedef boost::shared_ptr< ::second_assignment::Speed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::second_assignment::Speed_<ContainerAllocator> const> ConstPtr;

}; // struct Speed_

typedef ::second_assignment::Speed_<std::allocator<void> > Speed;

typedef boost::shared_ptr< ::second_assignment::Speed > SpeedPtr;
typedef boost::shared_ptr< ::second_assignment::Speed const> SpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::second_assignment::Speed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::second_assignment::Speed_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::second_assignment::Speed_<ContainerAllocator1> & lhs, const ::second_assignment::Speed_<ContainerAllocator2> & rhs)
{
  return lhs.acSpeed == rhs.acSpeed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::second_assignment::Speed_<ContainerAllocator1> & lhs, const ::second_assignment::Speed_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace second_assignment

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::second_assignment::Speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::second_assignment::Speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_assignment::Speed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::second_assignment::Speed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_assignment::Speed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::second_assignment::Speed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::second_assignment::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c34cf750d0cd671be992c30fdfbe639e";
  }

  static const char* value(const ::second_assignment::Speed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc34cf750d0cd671bULL;
  static const uint64_t static_value2 = 0xe992c30fdfbe639eULL;
};

template<class ContainerAllocator>
struct DataType< ::second_assignment::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "second_assignment/Speed";
  }

  static const char* value(const ::second_assignment::Speed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::second_assignment::Speed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 acSpeed\n"
;
  }

  static const char* value(const ::second_assignment::Speed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::second_assignment::Speed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acSpeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Speed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::second_assignment::Speed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::second_assignment::Speed_<ContainerAllocator>& v)
  {
    s << indent << "acSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.acSpeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SECOND_ASSIGNMENT_MESSAGE_SPEED_H
